databases:
  - name: postgres
    databaseName: hoztech_db
    user: hoztech_user
    plan: free
    region: sao
    ipAllowList: []  # Only allow internal connections

services:
  - type: redis
    name: redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []  # Only allow internal connections

  # Serviço Web (Django)
  - type: web
    name: django
    runtime: python
    plan: free
    region: sao
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "mysite.settings"

# Configurações Globais
preInstallCommand: |
  apt-get update && apt-get install -y build-essential python3-dev 