services:
  # Serviço Web (Django)
  - type: web
    name: hoztech.services
    env: python
    plan: free
    buildCommand: |
      echo "=== Instalando dependências ==="
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      echo "=== Preparando diretório staticfiles ==="
      rm -rf staticfiles
      mkdir -p staticfiles/images
      echo "=== Copiando arquivos estáticos ==="
      cp static/images/logo.png staticfiles/images/
      cp static/images/favicon.ico staticfiles/images/
      chmod 644 staticfiles/images/logo.png
      chmod 644 staticfiles/images/favicon.ico
      echo "=== Coletando arquivos estáticos ==="
      DJANGO_SETTINGS_MODULE=hoztechsite.settings python manage.py collectstatic --noinput
    startCommand: |
      echo "=== Iniciando Gunicorn ==="
      PYTHONPATH=/opt/render/project/src gunicorn hoztechsite.wsgi:application --bind=0.0.0.0:10000 --workers=2 --threads=2 --timeout=60 --log-level=debug --access-logfile=- --error-logfile=- --capture-output
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 2
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: hoztech-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_LOG_LEVEL
        value: "DEBUG"
      - key: SECURE_SSL_REDIRECT
        value: "False"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: STATIC_URL
        value: "/static/"
      - key: STATIC_ROOT
        value: "staticfiles"
      - key: MEDIA_URL
        value: "/media/"
      - key: MEDIA_ROOT
        value: "mediafiles"
      - key: DJANGO_SETTINGS_MODULE
        value: "hoztechsite.settings"
    healthCheckPath: /
    autoDeploy: true

  # Banco de Dados PostgreSQL
  - type: pserv
    name: hoztech-db
    env: postgresql
    region: sao
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: [] # Permitir todas as IPs
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

# Configurações Globais
preInstallCommand: |
  apt-get update && apt-get install -y build-essential python3-dev tree 