databases:
  - name: postgres
    databaseName: hoztech_db
    user: hoztech_user
    plan: free
    region: sao
    ipAllowList: []  # Only allow internal connections

services:
  - type: redis
    name: redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []  # Only allow internal connections

  # Serviço Web (Django)
  - type: web
    name: django
    runtime: python
    plan: free
    region: sao
    buildCommand: |
      # Install node.js dependencies
      npm install
      # Build Tailwind CSS
      npm run build
      # Run Django build script
      ./build.sh
    startCommand: "gunicorn hoztechsite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.x
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "hoztechsite.settings"
      - key: STATIC_ROOT
        value: "/opt/render/project/src/staticfiles"
      - key: STATIC_URL
        value: "/static/"

# Configurações Globais
preInstallCommand: |
  apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    nodejs \
    npm 