services:
  # Serviço Web (Django)
  - type: web
    name: hoztech.services
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install whitenoise
      rm -rf staticfiles/*
      mkdir -p staticfiles/images staticfiles/css
      cp -rv static/images/logo.png staticfiles/images/
      cp -rv static/images/favicon.ico staticfiles/images/
      cp -rv static/css/* staticfiles/css/
      find staticfiles -type f -exec chmod 644 {} \;
      find staticfiles -type d -exec chmod 755 {} \;
      DJANGO_SETTINGS_MODULE=hoztechsite.settings python manage.py collectstatic --noinput --clear
    startCommand: gunicorn hoztechsite.wsgi:application --bind=0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: hoztech-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: STATIC_URL
        value: "/static/"
      - key: STATIC_ROOT
        value: "/opt/render/project/src/staticfiles"
      - key: DJANGO_SETTINGS_MODULE
        value: "hoztechsite.settings"
      - key: WHITENOISE_USE_FINDERS
        value: "True"
      - key: WHITENOISE_MANIFEST_STRICT
        value: "False"

  # Banco de Dados PostgreSQL
  - type: pserv
    name: hoztech-db
    env: postgresql
    plan: free
    region: sao
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

# Configurações Globais
preInstallCommand: |
  apt-get update && apt-get install -y build-essential python3-dev tree 