services:
  # Serviço Web (Django)
  - type: web
    name: hoztech.services
    env: python
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install whitenoise
      echo "=== Iniciando processo de arquivos estáticos ==="
      echo "Verificando diretório static original:"
      ls -la static/images/
      echo "\nLimpando diretório staticfiles..."
      rm -rf /opt/render/project/src/staticfiles
      echo "\nExecutando collectstatic..."
      python manage.py collectstatic --noinput --clear
      echo "\nVerificando conteúdo do diretório staticfiles após coleta:"
      ls -la /opt/render/project/src/staticfiles/images/
      echo "\nVerificando permissões dos arquivos:"
      stat /opt/render/project/src/staticfiles/images/logo.png
      echo "\nVerificando hash do arquivo original vs coletado:"
      md5sum static/images/logo.png
      md5sum /opt/render/project/src/staticfiles/images/logo.png
      echo "=== Fim do processo de arquivos estáticos ==="
    startCommand: |
      echo "Verificando ambiente antes de iniciar:"
      echo "STATIC_ROOT=$STATIC_ROOT"
      echo "STATIC_URL=$STATIC_URL"
      echo "WHITENOISE_USE_FINDERS=$WHITENOISE_USE_FINDERS"
      echo "WHITENOISE_MANIFEST_STRICT=$WHITENOISE_MANIFEST_STRICT"
      echo "WHITENOISE_ALLOW_ALL_ORIGINS=$WHITENOISE_ALLOW_ALL_ORIGINS"
      gunicorn hoztechsite.wsgi:application --bind=0.0.0.0:10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: hoztech-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: STATIC_URL
        value: "/static/"
      - key: STATIC_ROOT
        value: "/opt/render/project/src/staticfiles"
      - key: DJANGO_SETTINGS_MODULE
        value: "hoztechsite.settings"
      - key: WHITENOISE_USE_FINDERS
        value: "True"
      - key: WHITENOISE_MANIFEST_STRICT
        value: "False"
      - key: WHITENOISE_ALLOW_ALL_ORIGINS
        value: "True"

  # Banco de Dados PostgreSQL
  - type: pserv
    name: hoztech-db
    env: postgresql
    plan: free
    region: sao
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

# Configurações Globais
preInstallCommand: |
  apt-get update && apt-get install -y build-essential python3-dev tree 