services:
  # Serviço Web (Django)
  - type: web
    name: hoztech.services
    env: python
    plan: free
    buildCommand: |
      echo "=== Verificando estrutura do projeto ==="
      pwd
      ls -la
      echo "=== Python Version ==="
      python --version
      echo "=== Pip Version ==="
      pip --version
      echo "=== Instalando dependências ==="
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      echo "=== Preparando diretório staticfiles ==="
      rm -rf staticfiles
      mkdir -p staticfiles
      echo "=== Coletando arquivos estáticos ==="
      python manage.py collectstatic --noinput
      echo "=== Verificando arquivos coletados ==="
      ls -la staticfiles/
      echo "=== Verificando imagens ==="
      ls -la staticfiles/images/
      echo "=== Aplicando migrações ==="
      python manage.py migrate
    startCommand: |
      echo "=== Iniciando Gunicorn ==="
      gunicorn hoztechsite.wsgi:application --workers 2 --threads 2 --timeout 60 --log-level debug --error-logfile - --access-logfile - --capture-output
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 2
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: hoztech-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_LOG_LEVEL
        value: "DEBUG"
      - key: SECURE_SSL_REDIRECT
        value: "False"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: STATIC_URL
        value: "/static/"
      - key: STATIC_ROOT
        value: "staticfiles"
      - key: MEDIA_URL
        value: "/media/"
      - key: MEDIA_ROOT
        value: "mediafiles"
      - key: DJANGO_SETTINGS_MODULE
        value: "hoztechsite.settings"
    healthCheckPath: /
    autoDeploy: true

  # Banco de Dados PostgreSQL
  - type: pserv
    name: hoztech-db
    env: postgresql
    region: sao
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: [] # Permitir todas as IPs
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

# Configurações Globais
preInstallCommand: |
  apt-get update && apt-get install -y build-essential python3-dev tree 