databases:
  - name: hoztechsite-db
    databaseName: hoztechsite
    user: hoztechsite
    plan: free

services:
  - type: redis
    name: redis
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: []  # Only allow internal connections

  # Serviço Web (Django)
  - type: web
    name: hoztechsite
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn hoztechsite.wsgi:application --workers 2 --threads 2 --timeout 60
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: hoztechsite-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true
      - key: SECURE_HSTS_SECONDS
        value: 31536000
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: true
      - key: SECURE_HSTS_PRELOAD
        value: true
    healthCheckPath: /health/
    autoDeploy: true
    domains:
      - hoztech.com
      - www.hoztech.com
    envVars:
      - key: WEB_CONCURRENCY
        value: 2
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
      targetCPUPercent: 80

# Configurações Globais
preInstallCommand: |
  apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    nodejs \
    npm 