# Generated by Django 5.2.1 on 2025-06-01 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField()),
                ('h1_count', models.IntegerField(default=0)),
                ('h2_count', models.IntegerField(default=0)),
                ('h3_count', models.IntegerField(default=0)),
                ('image_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('internal_links', models.IntegerField(default=0)),
                ('external_links', models.IntegerField(default=0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('page_speed_score', models.FloatField(blank=True, null=True)),
                ('mobile_friendly_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SEO Metrics',
                'verbose_name_plural': 'SEO Metrics',
                'ordering': ['-last_checked'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('json', 'JSON'), ('pdf', 'PDF')], max_length=10)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.FileField(upload_to='analytics_exports/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Export',
                'verbose_name_plural': 'Analytics Exports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('referrer', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='core.session')),
            ],
            options={
                'verbose_name': 'Page View',
                'verbose_name_plural': 'Page Views',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('domain', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('secure', models.BooleanField(default=False)),
                ('httponly', models.BooleanField(default=False)),
                ('samesite', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookies', to='core.session')),
            ],
            options={
                'verbose_name': 'Cookie',
                'verbose_name_plural': 'Cookies',
                'ordering': ['-created_at'],
            },
        ),
    ]
