# Generated by Django 5.2.4 on 2025-08-03 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40, unique=True)),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("user_agent", models.TextField()),
                ("referrer", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_activity", models.DateTimeField(auto_now=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(db_index=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("time_spent", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page View",
                "verbose_name_plural": "Page Views",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cookie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("value", models.TextField()),
                ("domain", models.CharField(db_index=True, max_length=255)),
                ("path", models.CharField(max_length=255)),
                ("expires", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("secure", models.BooleanField(default=False)),
                ("httponly", models.BooleanField(default=False)),
                ("samesite", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cookies",
                        to="core.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cookie",
                "verbose_name_plural": "Cookies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel"),
                            ("json", "JSON"),
                            ("pdf", "PDF"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_range_start", models.DateField(db_index=True)),
                ("date_range_end", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("file_path", models.FileField(upload_to="analytics_exports/")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Export",
                "verbose_name_plural": "Analytics Exports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["date_range_start", "date_range_end"],
                        name="core_analyt_date_ra_233c65_idx",
                    ),
                    models.Index(
                        fields=["created_at", "is_active"],
                        name="core_analyt_created_2a9c5a_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="core_analyt_user_id_3c3778_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SEOMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(db_index=True, unique=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("meta_description", models.TextField()),
                ("h1_count", models.IntegerField(default=0)),
                ("h2_count", models.IntegerField(default=0)),
                ("h3_count", models.IntegerField(default=0)),
                ("image_count", models.IntegerField(default=0)),
                ("word_count", models.IntegerField(default=0)),
                ("internal_links", models.IntegerField(default=0)),
                ("external_links", models.IntegerField(default=0)),
                ("last_checked", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "page_speed_score",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                (
                    "mobile_friendly_score",
                    models.FloatField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seo_metrics_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seo_metrics_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Metrics",
                "verbose_name_plural": "SEO Metrics",
                "ordering": ["-last_checked"],
                "indexes": [
                    models.Index(
                        fields=["url", "is_active"], name="core_seomet_url_6236b0_idx"
                    ),
                    models.Index(
                        fields=["last_checked", "is_active"],
                        name="core_seomet_last_ch_21013b_idx",
                    ),
                    models.Index(
                        fields=["page_speed_score", "mobile_friendly_score"],
                        name="core_seomet_page_sp_5eed05_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["created_at", "is_active"],
                name="core_sessio_created_4b91ff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["last_activity", "is_active"],
                name="core_sessio_last_ac_da04a3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["ip_address", "is_active"],
                name="core_sessio_ip_addr_4f6492_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["url", "created_at"], name="core_pagevi_url_9cd6ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(
                fields=["created_at", "is_active"],
                name="core_pagevi_created_d0d1cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cookie",
            index=models.Index(
                fields=["name", "domain"], name="core_cookie_name_3055cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cookie",
            index=models.Index(
                fields=["created_at", "is_active"],
                name="core_cookie_created_890904_idx",
            ),
        ),
    ]
