# Generated by Django 5.2.4 on 2025-08-05 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Config",
                "verbose_name_plural": "WhatsApp Configs",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("is_blocked", models.BooleanField(db_index=True, default=False)),
                ("is_my_contact", models.BooleanField(db_index=True, default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "WhatsApp Contact",
                "verbose_name_plural": "WhatsApp Contacts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "is_active"],
                        name="core_whatsa_phone_n_c702e9_idx",
                    ),
                    models.Index(
                        fields=["is_my_contact", "is_blocked"],
                        name="core_whatsa_is_my_c_69d1a0_idx",
                    ),
                    models.Index(
                        fields=["created_at", "is_active"],
                        name="core_whatsa_created_3aeff7_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativa"),
                            ("paused", "Pausada"),
                            ("completed", "Concluída"),
                            ("error", "Erro"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("current_step", models.IntegerField(default=0)),
                ("context_data", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("last_activity", models.DateTimeField(auto_now=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="core.whatsappcontact",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Session",
                "verbose_name_plural": "WhatsApp Sessions",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("incoming", "Recebida"), ("outgoing", "Enviada")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("image", "Imagem"),
                            ("document", "Documento"),
                            ("audio", "Áudio"),
                            ("video", "Vídeo"),
                            ("location", "Localização"),
                            ("contact", "Contato"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("media_url", models.URLField(blank=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("is_automated", models.BooleanField(db_index=True, default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.whatsappsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Message",
                "verbose_name_plural": "WhatsApp Messages",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.whatsappcontact",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.whatsappsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Log",
                "verbose_name_plural": "WhatsApp Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("variables", models.JSONField(blank=True, default=list)),
                ("step_number", models.IntegerField(db_index=True, default=0)),
                ("delay_seconds", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Template",
                "verbose_name_plural": "WhatsApp Templates",
                "ordering": ["step_number", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="whatsappsession",
            index=models.Index(
                fields=["session_id", "is_active"],
                name="core_whatsa_session_35251c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappsession",
            index=models.Index(
                fields=["status", "is_active"], name="core_whatsa_status_a9fcfa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappsession",
            index=models.Index(
                fields=["started_at", "status"], name="core_whatsa_started_c4db3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappsession",
            index=models.Index(
                fields=["last_activity", "is_active"],
                name="core_whatsa_last_ac_edf07d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["message_id", "is_active"],
                name="core_whatsa_message_e3f123_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["direction", "is_automated"],
                name="core_whatsa_directi_99e6d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["timestamp", "is_active"], name="core_whatsa_timesta_ec9a5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["session", "timestamp"], name="core_whatsa_session_cdbad7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapplog",
            index=models.Index(
                fields=["level", "timestamp"], name="core_whatsa_level_c2e3b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapplog",
            index=models.Index(
                fields=["timestamp", "is_active"], name="core_whatsa_timesta_8be4e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapplog",
            index=models.Index(
                fields=["session", "timestamp"], name="core_whatsa_session_5779df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapptemplate",
            index=models.Index(
                fields=["name", "is_active"], name="core_whatsa_name_976e56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapptemplate",
            index=models.Index(
                fields=["step_number", "is_active"],
                name="core_whatsa_step_nu_8c914a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsapptemplate",
            index=models.Index(
                fields=["created_at", "is_active"],
                name="core_whatsa_created_ec874c_idx",
            ),
        ),
    ]
