# Generated by Django 5.2.1 on 2025-06-04 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsexport',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='cookie',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='seometrics',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_metrics_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seometrics',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='seometrics',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_metrics_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analyticsexport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='analyticsexport',
            name='date_range_end',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='analyticsexport',
            name='date_range_start',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='analyticsexport',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='domain',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='expires',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='url',
            field=models.URLField(db_index=True),
        ),
        migrations.AlterField(
            model_name='seometrics',
            name='last_checked',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='seometrics',
            name='mobile_friendly_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='seometrics',
            name='page_speed_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='seometrics',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='seometrics',
            name='url',
            field=models.URLField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='analyticsexport',
            index=models.Index(fields=['date_range_start', 'date_range_end'], name='core_analyt_date_ra_233c65_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsexport',
            index=models.Index(fields=['created_at', 'is_active'], name='core_analyt_created_2a9c5a_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsexport',
            index=models.Index(fields=['user', 'is_active'], name='core_analyt_user_id_3c3778_idx'),
        ),
        migrations.AddIndex(
            model_name='cookie',
            index=models.Index(fields=['name', 'domain'], name='core_cookie_name_3055cb_idx'),
        ),
        migrations.AddIndex(
            model_name='cookie',
            index=models.Index(fields=['created_at', 'is_active'], name='core_cookie_created_890904_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['url', 'created_at'], name='core_pagevi_url_9cd6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['created_at', 'is_active'], name='core_pagevi_created_d0d1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='seometrics',
            index=models.Index(fields=['url', 'is_active'], name='core_seomet_url_6236b0_idx'),
        ),
        migrations.AddIndex(
            model_name='seometrics',
            index=models.Index(fields=['last_checked', 'is_active'], name='core_seomet_last_ch_21013b_idx'),
        ),
        migrations.AddIndex(
            model_name='seometrics',
            index=models.Index(fields=['page_speed_score', 'mobile_friendly_score'], name='core_seomet_page_sp_5eed05_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['created_at', 'is_active'], name='core_sessio_created_4b91ff_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['last_activity', 'is_active'], name='core_sessio_last_ac_da04a3_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['ip_address', 'is_active'], name='core_sessio_ip_addr_4f6492_idx'),
        ),
    ]
